name: Create Release Branch

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      MY_GITHUB_TOKEN:
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # tüm geçmişi al ki branch oluştururken sorun çıkmasın

      - name: Create release branch
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          VERSION: ${{ inputs.version }}
        run: |
          BRANCH_NAME="release-v$VERSION"
          echo "Creating new branch: $BRANCH_NAME"

          # Mevcut HEAD'den yeni branch oluştur
          git checkout -b "$BRANCH_NAME"

          # Push et
          git push origin "$BRANCH_NAME"

          echo "✅ Branch '$BRANCH_NAME' created and pushed."
