# .github/workflows/notify-teams.yml
name: Notify Teams

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      TEAMS_WEBHOOK:
        required: true
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Mesajı yazdır
        run: echo "Gelen mesaj ${{ inputs.message }}"

      - name: Webhook'a gönder
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"text\": \"${{ inputs.message }}\"}" \
               ${{ secrets.TEAMS_WEBHOOK }}
